#!/bin/sh

# This code is part of the TrinityX software suite
# Copyright (C) 2025  ClusterVision Solutions b.v.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

###
#
# Copy this file as /etc/bash_completion.d/lrack and start a new shell.
# Regenerate with:
#   shtab --shell=bash --prog lrack --prefix lrack utils.lrack.get_parser
# Live rack/device name completion additionally requires argcomplete:
#   eval "$(register-python-argcomplete lrack)"
#
####

# AUTOMATICALLY GENERATED by `shtab`

_shtab_lrack_subparsers=('list' 'show' 'add' 'change' 'rename' 'remove' 'place' 'unplace' 'resize' 'orient' 'inventory' 'pool')

_shtab_lrack_option_strings=('-h' '--help' '-V' '--version' '-v' '--verbose' '-R' '--raw' '-e' '--export' '-i' '--import' '-r' '--rack' '-f' '--force')
_shtab_lrack_list_option_strings=('-h' '--help')
_shtab_lrack_show_option_strings=('-h' '--help' '-F' '--full' '-s' '--summary' '-M' '--map' '-c' '--columns' '-w' '--width')
_shtab_lrack_add_option_strings=('-h' '--help' '-s' '--size' '-d' '--order' '-m' '--room' '-t' '--site')
_shtab_lrack_change_option_strings=('-h' '--help' '-s' '--size' '-d' '--order' '-m' '--room' '-t' '--site')
_shtab_lrack_rename_option_strings=('-h' '--help')
_shtab_lrack_remove_option_strings=('-h' '--help')
_shtab_lrack_place_option_strings=('-h' '--help' '-r' '--rack' '-p' '--position' '-o' '--orientation' '-H' '--height' '-f' '--force')
_shtab_lrack_unplace_option_strings=('-h' '--help')
_shtab_lrack_resize_option_strings=('-h' '--help' '-H' '--height')
_shtab_lrack_orient_option_strings=('-h' '--help' '-o' '--orientation')
_shtab_lrack_inventory_option_strings=('-h' '--help')
_shtab_lrack_pool_option_strings=('-h' '--help')



_shtab_lrack_pos_0_choices=('list' 'show' 'add' 'change' 'rename' 'remove' 'place' 'unplace' 'resize' 'orient' 'inventory' 'pool')
_shtab_lrack_add__d_choices=('ascending' 'descending')
_shtab_lrack_add___order_choices=('ascending' 'descending')
_shtab_lrack_change__d_choices=('ascending' 'descending')
_shtab_lrack_change___order_choices=('ascending' 'descending')
_shtab_lrack_place__o_choices=('front' 'back')
_shtab_lrack_place___orientation_choices=('front' 'back')
_shtab_lrack_orient__o_choices=('front' 'back')
_shtab_lrack_orient___orientation_choices=('front' 'back')
_shtab_lrack_inventory_pos_0_choices=('configured' 'unconfigured')

_shtab_lrack_pos_0_nargs=A...
_shtab_lrack__h_nargs=0
_shtab_lrack___help_nargs=0
_shtab_lrack__V_nargs=0
_shtab_lrack___version_nargs=0
_shtab_lrack__v_nargs=0
_shtab_lrack___verbose_nargs=0
_shtab_lrack__R_nargs=0
_shtab_lrack___raw_nargs=0
_shtab_lrack__e_nargs=?
_shtab_lrack___export_nargs=?
_shtab_lrack__f_nargs=0
_shtab_lrack___force_nargs=0
_shtab_lrack_list__h_nargs=0
_shtab_lrack_list___help_nargs=0
_shtab_lrack_list__v_nargs=0
_shtab_lrack_list___verbose_nargs=0
_shtab_lrack_list__R_nargs=0
_shtab_lrack_list___raw_nargs=0
_shtab_lrack_show_pos_0_nargs=*
_shtab_lrack_show__h_nargs=0
_shtab_lrack_show___help_nargs=0
_shtab_lrack_show__F_nargs=0
_shtab_lrack_show___full_nargs=0
_shtab_lrack_show__s_nargs=0
_shtab_lrack_show___summary_nargs=0
_shtab_lrack_show__M_nargs=0
_shtab_lrack_show___map_nargs=0
_shtab_lrack_show__v_nargs=0
_shtab_lrack_show___verbose_nargs=0
_shtab_lrack_show__R_nargs=0
_shtab_lrack_show___raw_nargs=0
_shtab_lrack_add__h_nargs=0
_shtab_lrack_add___help_nargs=0
_shtab_lrack_add__v_nargs=0
_shtab_lrack_add___verbose_nargs=0
_shtab_lrack_add__R_nargs=0
_shtab_lrack_add___raw_nargs=0
_shtab_lrack_change__h_nargs=0
_shtab_lrack_change___help_nargs=0
_shtab_lrack_change__v_nargs=0
_shtab_lrack_change___verbose_nargs=0
_shtab_lrack_change__R_nargs=0
_shtab_lrack_change___raw_nargs=0
_shtab_lrack_rename__h_nargs=0
_shtab_lrack_rename___help_nargs=0
_shtab_lrack_rename__v_nargs=0
_shtab_lrack_rename___verbose_nargs=0
_shtab_lrack_rename__R_nargs=0
_shtab_lrack_rename___raw_nargs=0
_shtab_lrack_remove__h_nargs=0
_shtab_lrack_remove___help_nargs=0
_shtab_lrack_remove__v_nargs=0
_shtab_lrack_remove___verbose_nargs=0
_shtab_lrack_remove__R_nargs=0
_shtab_lrack_remove___raw_nargs=0
_shtab_lrack_place__h_nargs=0
_shtab_lrack_place___help_nargs=0
_shtab_lrack_place__f_nargs=0
_shtab_lrack_place___force_nargs=0
_shtab_lrack_place__v_nargs=0
_shtab_lrack_place___verbose_nargs=0
_shtab_lrack_place__R_nargs=0
_shtab_lrack_place___raw_nargs=0
_shtab_lrack_unplace__h_nargs=0
_shtab_lrack_unplace___help_nargs=0
_shtab_lrack_unplace__v_nargs=0
_shtab_lrack_unplace___verbose_nargs=0
_shtab_lrack_unplace__R_nargs=0
_shtab_lrack_unplace___raw_nargs=0
_shtab_lrack_resize__h_nargs=0
_shtab_lrack_resize___help_nargs=0
_shtab_lrack_resize__v_nargs=0
_shtab_lrack_resize___verbose_nargs=0
_shtab_lrack_resize__R_nargs=0
_shtab_lrack_resize___raw_nargs=0
_shtab_lrack_orient__h_nargs=0
_shtab_lrack_orient___help_nargs=0
_shtab_lrack_orient__v_nargs=0
_shtab_lrack_orient___verbose_nargs=0
_shtab_lrack_orient__R_nargs=0
_shtab_lrack_orient___raw_nargs=0
_shtab_lrack_inventory__h_nargs=0
_shtab_lrack_inventory___help_nargs=0
_shtab_lrack_inventory__v_nargs=0
_shtab_lrack_inventory___verbose_nargs=0
_shtab_lrack_inventory__R_nargs=0
_shtab_lrack_inventory___raw_nargs=0
_shtab_lrack_pool__h_nargs=0
_shtab_lrack_pool___help_nargs=0
_shtab_lrack_pool__v_nargs=0
_shtab_lrack_pool___verbose_nargs=0
_shtab_lrack_pool__R_nargs=0
_shtab_lrack_pool___raw_nargs=0


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_lrack() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_lrack
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_lrack lrack
