#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This file is the entry point for provisioning
"""

__author__      = 'Antoine Schonewille'
__copyright__   = 'Copyright 2023, Luna2 Project'
__license__     = 'GPL'
__version__     = '2.0'
__maintainer__  = 'Dev-team'
__email__       = 'antoine.schonewille@clustervision.com'
__status__      = 'Development'




#from flask import json, request
from builtins import dict
import requests
import re

CONF=dict()

regex = re.compile("^(.[^=]+)\s+?=\s+?(.*)$")
with open("/trinity/local/luna/config/luna.ini") as f:
    for line in f:
        result = regex.match(line)
        if (result):
            CONF[result.group(1)]=result.group(2)

for key in CONF:
    print(key, '->', CONF[key])

token_credentials = {'username': "'"+CONF['USERNAME']+"'",'password': "'"+CONF['PASSWORD']+"'"}

x = requests.post('http://'+CONF["ENDPOINT"]+'/token', json = token_credentials)
print(x.status_code)

r = requests.get('http://'+CONF["ENDPOINT"]+'/get/control/power/node001') #, auth=('user', 'pass'))
print(r.status_code)
